### PR TITLE
Viite 1411 creation of corrective road address projects

### PR DESCRIPTION
**Pull request by pedrosag**

### CODE REVIEW

**Comment by pedrosag** [comment]
Preparing to run the test suit on jenkins ATM.

**Comment by pedrosag** [comment]
One test failing on build 1089 trying to correct it now.

**Comment by pedrosag** [comment]
Ok all tests fixed, build 1091 on Jenkins.

**Comment by pedrosag** [comment]
@skosonen I updated my Idea recently and a very UNWELCOME change it brought was that every time I do a commit with it it triggers a "reformat code".
I have yet to find where to customise to it be OFF by default :\

**Comment by Campanha** [comment]
Its it possible to add some test for it?

**Comment by skosonen** [comment]
@pedrosag I changed Javascript formatting so that indentation is two spaces instead of the default four.

**Comment by pedrosag** [comment]
Backend tests are passing (Jenkins build 1230).
Frontend tests are passing.

**Comment by pedrosag** [comment]
Tagged as DO_NOT_MERGE because it was deemed a big change when the focus was not on the projects.
Waiting for go ahead to merge instructions.

**Comment by skosonen** [comment]
And sometimes it fails in:
 when new project link is selected
      1) Check if there form inputs are empty

**Comment by tomixii** [comment]
Weir, tests pass for me.

**Comment by pedrosag** [comment]
Looking into it.

**Comment by pedrosag** [comment]
@skosonen 
Curious I didn't got the phantomJS timeout but instead 3 out of 10 time it would fail in the cancel the split phase.
Specifically:



Running "mocha:viite_integration" (mocha) task
Testing: http://127.0.0.1:9003/test/integration-tests.html
JQMIGRATE: Migrate is installed, version 1.4.0


  when loading application
    Selecting the first floating
      √ check if the form opened for the correct floatings
    Clicking the "Valinta" button
      √ check that the "Valinta" was pressed and the unknowns are "forward"
    Selecting a unknown road to transfer the floatings
      √ Check if the unknown road was selected via form
      √ Check if the unknown road was selected via Layers
    Click the Siirrä button to start the simulation
      √ Confirm that the form changed
      √ Verify that the simulated road addresses are simulated
    Click the Tallenna button to save the simulated data
      √ Verify that the previous unknown link is now no longer unknown and there is only one feature

  when making a split
    select cut tool and make a split
      √ check split form data
    cancel the split
      1) verify that split form was cleared

  when click on the Tieosoiteprojektit button
    √ open project list window
    when clicking in new project button
      √ open project form info
    when clicking in reserve aka Varaa button
      √ Jatka button should be enabled
    when clicking in next aka Seuraava button and select one reserved link
      √ Check if the project link was selected
    when new project link is selected
      √ Check if there form inputs are empty
    when clicking Peruuta button
      √ Check if it change to the road form


  14 passing (8s)
  1 failing

  1) when making a split
       cancel the split
         verify that split form was cleared:

      expected 1 to equal 0
      + expected - actual

      -1
      +0

  assert@http://127.0.0.1:9003/node_modules/chai/chai.js:873:67
  assertEqual@http://127.0.0.1:9003/node_modules/chai/chai.js:1380:18
  http://127.0.0.1:9003/node_modules/chai/chai.js:3627:30
  http://127.0.0.1:9003/test/integration-tests/SplittingRoadAddressSpec.js:61:54
  callFn@http://127.0.0.1:9003/node_modules/mocha/mocha.js:4490:25
  run@http://127.0.0.1:9003/node_modules/mocha/mocha.js:4482:13
  runTest@http://127.0.0.1:9003/node_modules/mocha/mocha.js:4996:13
  http://127.0.0.1:9003/node_modules/mocha/mocha.js:5114:19
  next@http://127.0.0.1:9003/node_modules/mocha/mocha.js:4910:16
  http://127.0.0.1:9003/node_modules/mocha/mocha.js:4920:11
  next@http://127.0.0.1:9003/node_modules/mocha/mocha.js:4844:16
  http://127.0.0.1:9003/node_modules/mocha/mocha.js:4888:9
  timeslice@http://127.0.0.1:9003/node_modules/mocha/mocha.js:82:27



>> 1/15 tests failed (8.09s)
An error occured. { Error: spawn growlnotify ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn growlnotify',
  path: 'growlnotify',
  spawnargs:
   [ '/i:C:\\Users\\pedrosag\\Repos\\digiroad2\\node_modules\\grunt-mocha\\growl\\error.png',
     '1/15 tests failed (8.09s)',
     '/t:Failure in viite_integration' ] }
An error occured. { Error: spawn growlnotify ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn growlnotify',
  path: 'growlnotify',
  spawnargs:
   [ '/i:C:\\Users\\pedrosag\\Repos\\digiroad2\\node_modules\\grunt-mocha\\growl\\error.png',
     '1/15 tests failed (8.09s)',
     '/t:1/15 tests failed (8.09s)' ] }
Warning: Task "mocha:viite_integration" failed. Use --force to continue.

Aborted due to warnings.

**Comment by pedrosag** [comment]
@skosonen I don't know what happened, but after a re-download of the branch I am not having the problem I reported, neither the timeout...

Soo I am gonna merge master into this, and solve conflicts.

**Comment by pedrosag** [comment]
Please do not merge, don't know if it was the last merge commit or another one prior that introduced some errors:

error] /data1/workspace/Run Fixture Reset/digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala:192: type mismatch;
[error]  found   : Boolean(false)
[error]  required: fi.liikennevirasto.viite.dao.FloatingReason
[error]         floating = false, Seq(Point(0.0, startAddrM), Point(0.0, endAddrM)), projectId, status, RoadType.PublicRoad,
[error]                    ^
[error] /data1/workspace/Run Fixture Reset/digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/ProjectServiceSpec.scala:2321: type mismatch;
[error]  found   : Boolean(false)
[error]  required: fi.liikennevirasto.viite.dao.FloatingReason
[error]         startDate, None, Option("TR"), linkId, 0.0, 10.0, SideCode.TowardsDigitizing, 1476392565000L, (None, None), floating = false,
[error]                                                                                                                                ^
[error] /data1/workspace/Run Fixture Reset/digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/OverlapDataFixture.scala:81: could not find implicit value for parameter rconv: slick.jdbc.GetResult[fi.liikennevirasto.viite.util.OverlapRoadAddress]
[error]       """.as[OverlapRoadAddress].list
[error]             ^
[error] /data1/workspace/Run Fixture Reset/digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/OverlapDataFixture.scala:94: could not find implicit value for parameter rconv: slick.jdbc.GetResult[fi.liikennevirasto.viite.util.OverlapRoadAddress]
[error]     """.as[OverlapRoadAddress].list
[error]           ^
[error] /data1/workspace/Run Fixture Reset/digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/OverlapDataFixture.scala:100: could not find implicit value for parameter rconv: slick.jdbc.GetResult[fi.liikennevirasto.viite.util.OverlapRoadAddress]
[error]       Q.queryNA[OverlapRoadAddress](s"""
[error]                                    ^
[error] /data1/workspace/Run Fixture Reset/digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/OverlapDataFixture.scala:120: could not find implicit value for parameter rconv: slick.jdbc.GetResult[fi.liikennevirasto.viite.util.OverlapRoadAddress]
[error]       """.as[OverlapRoadAddress].list
[error]             ^
[error] /data1/workspace/Run Fixture Reset/digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/OverlapDataFixture.scala:126: could not find implicit value for parameter rconv: slick.jdbc.GetResult[fi.liikennevirasto.viite.util.OverlapRoadAddress]
[error]       """.as[OverlapRoadAddress].list
[error]             ^
[error] /data1/workspace/Run Fixture Reset/digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/OverlapDataFixture.scala:135: could not find implicit value for parameter rconv: slick.jdbc.GetResult[fi.liikennevirasto.viite.util.OverlapRoadAddress]
[error]       """.as[OverlapRoadAddress].list
[error]             ^
[error] /data1/workspace/Run Fixture Reset/digiroad2-viite/src/test/scala/fi/liikennevirasto/viite/util/OverlapDataFixture.scala:141: could not find implicit value for parameter rconv: slick.jdbc.GetResult[fi.liikennevirasto.viite.util.OverlapRoadAddress]
[error]       """.as[OverlapRoadAddress].list

**Comment by pedrosag** [comment]
Errors solved, running the tests.

**Comment by skosonen** [comment]
Tests pass. Check build #1464 on Jenkins.

**Comment by pedrosag** [comment]
Tests are currently passing on Jenkins:
http://172.17.201.56:8888/job/Run%20OTH%20+%20Viite%20Tests/1464/console

Also UI tests seem to pass as well:
image

**Pull request merged**
