### PR TITLE
VIITE-1394 new validation to check the previous road part outside of the project

### PR DESCRIPTION
**Pull request by tomixii**
Added new validation: Viite checks if there is end of road discontinuity on the previous road parts which are not in the project. Side note: Let's try to keep function names as describing as possible. I used a lot of time debugging code because of few functions didn't do what i expected them to do by their names.

### CODE REVIEW

**Comment by leirasf** [comment]
This needs to be checked with the task VIITE-1401, VIITE-1391 and VIITE-1392

**Comment by Campanha** [comment]
code seems correct to me, but i have tested locally and its not working for the test i did

**Comment by Campanha** [comment]
i also noticed that im getting some js errors due to no supported javascript language feature

**Comment by tomixii** [comment]
Weird, it works fine for me and I'm not getting any js errors. How did you test it?

**Comment by Campanha** [comment]
About the test i tried to create one new last part for roadnumber 1, (the part 37, since the last existing part is the 36) with 2 links, 1 for track 1 and others for track 2. 

About the js error you can for e.g. check the viite build 364 last 4 rows info in output.

**Pull request merged**
