### PR TITLE
VIITE-2255 Two-track road direction

### PR DESCRIPTION
**Pull request by skosonen**

### CODE REVIEW

**Comment by skosonen** [comment]
Three tests fail now:

Test orderProjectLinksTopologyByGeometry When choosing the same track when there is 2 connected Then links with only one with same track code should be picked *** FAILED ***

Test defaultSectionCalculatorStrategy.findStartingPoints() When adding one (New) link with inverted geometry before the existing (Transfer) road but where the first link was terminated Then the road should still maintain the previous existing direction *** FAILED ***

Test defaultSectionCalculatorStrategy.findStartingPoints() When adding one (New) link before the existing (Transfer) road but where the first link was terminated Then the road should still maintain the previous existing direction *** FAILED ***

**Comment by skosonen** [comment]
Now four tests are failing. Better to merge changes done by Ricardo first and then work on this one.

**Comment by skosonen** [comment]
Now 7 tests fail.

**Comment by skosonen** [comment]
One broken test left: ProjectSectionCalculatorSpec:881

**Comment by Campanha** [comment]
all tests passing at: http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/168/consoleFull
(master branch included)

**Pull request merged**
