### PR TITLE
VIITE-1881 end date like in TR

### PR DESCRIPTION
**Pull request by skosonen**

### CODE REVIEW

**Comment by skosonen** [comment]
Tests pass on Jenkins: #435

**Comment by skosonen** [comment]
Roadway end_date is not yet set correctly when bringing project to roadway-table.

**Comment by skosonen** [comment]
Tests pass on Jenkins: #437

**Comment by skosonen** [comment]
This will be merged to VIITE-1842 branch and then merged together with that to master.

**Comment by hestrompa** [comment]
I will close this PR, it is included in VIITE-1842

**Pull request closed without merging**
