### PR TITLE
Viite 1483 form shows geometry source of link

### PR DESCRIPTION
**Pull request by pedrosag**

### CODE REVIEW

**Comment by Campanha** [comment]
we should revert the merge from master as there is one "ambiguousFields" variable not defined

**Comment by skosonen** [comment]
@Campanha no need to revert the whole merge but just fix the problem.

**Comment by skosonen** [comment]
All tests pass on Jenkins #1278.

**Comment by skosonen** [comment]
Tests pass on Jenkins. Check build #1281.

**Comment by skosonen** [comment]
When I run UI tests locally on browser, I get error in console:
`when making a split
WebConsole.js:110 url
WebConsole.js:110 select cut tool and make a split
WebConsole.js:110 url
WebConsole.js:110 "before all" hook
WebConsole.js:110 TypeError: Cannot read property 'descriptionFI' of undefined
    at SplitForm.js:61
    at arrayMap (index.js:1406)
    at map (index.js:6710)
    at interceptor (index.js:12240)
    at thru (index.js:5927)
    at baseWrapperValue (index.js:2768)
    at LazyWrapper.lazyValue [as value] (index.js:1077)
    at baseWrapperValue (index.js:2761)
    at LodashWrapper.wrapperValue (index.js:6124)
    at selectedProjectLinkTemplate (SplitForm.js:62)`

**Comment by pedrosag** [comment]
Ui tests are passing now:

capture

**Pull request merged**
