### PR TITLE
VIITE-1891 reversing BeforeAfter updates

### PR DESCRIPTION
**Pull request by Campanha**

### CODE REVIEW

**Comment by Campanha** [comment]
tests passing: http://livibuild04.vally.local/jenkins/job/viite/job/Fixture-Reset/104/console

**Comment by Campanha** [comment]
tests passing at : http://livibuild04.vally.local/jenkins/job/viite/job/Run-Tests/56/console

**Comment by kohonenm** [comment]
It seems there are many commits with other branches under VIITE-1891 title. At " first check", are those commits dependable to each other or not ? Are those other VIITE- branches already merged to master ?

**Comment by Campanha** [comment]
> It seems there are many commits with other branches under VIITE-1891 title. At " first check", are those commits dependable to each other or not ? Are those other VIITE- branches already merged to master ?

Yes, they were already merged. And master is already merged into this one.

**Pull request merged**
